# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-11 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='app.Genre'),
        ),
        migrations.AlterField(
            model_name='trackgenre',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='app.Tracks'),
        ),
    ]
