# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-11 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170212_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='date_modified',
        ),
    ]
